/**
 * Platform configurations for CreateHub
 */

export const PLATFORMS = {
  twitter: {
    id: "twitter",
    label: "X (Twitter)",
    shortLabel: "X",
    icon: "FaXTwitter",
    color: "#000000",
    darkColor: "#ffffff",
    contentTypes: [
      { id: "tweet", label: "Tweet yaz" },
      { id: "quote", label: "Alıntı" },
      { id: "reply", label: "Yanıt" },
      { id: "thread", label: "Thread" },
    ],
    endpoint: "/api/generate/tweet",
    placeholder: "Tweet konusu yaz veya bir fikir paylaş...",
    hasPersona: true,
    hasTone: true,
    hasKnowledge: true,
    hasStyleProfile: true,
    hasUltraMode: true,
  },
  linkedin: {
    id: "linkedin",
    label: "LinkedIn",
    shortLabel: "LinkedIn",
    icon: "FaLinkedinIn",
    color: "#0A66C2",
    darkColor: "#0A66C2",
    contentTypes: [
      { id: "post", label: "Post yaz" },
      { id: "carousel", label: "Carousel" },
      { id: "hook", label: "Hook üret" },
    ],
    endpoint: "/api/generate/linkedin",
    placeholder: "LinkedIn post konusu yaz...",
    hasPersona: true,
    hasTone: false,
    hasKnowledge: false,
    hasStyleProfile: false,
    hasUltraMode: false,
  },
  instagram: {
    id: "instagram",
    label: "Instagram",
    shortLabel: "Instagram",
    icon: "FaInstagram",
    color: "#E4405F",
    darkColor: "#E4405F",
    contentTypes: [
      { id: "caption", label: "Caption" },
      { id: "reel_script", label: "Reel Script" },
      { id: "story", label: "Story" },
      { id: "hashtag", label: "Hashtag" },
    ],
    endpoint: "/api/generate/instagram/caption",
    placeholder: "Instagram içeriği için konu yaz...",
    hasPersona: false,
    hasTone: false,
    hasKnowledge: false,
    hasStyleProfile: false,
    hasUltraMode: false,
  },
  youtube: {
    id: "youtube",
    label: "YouTube",
    shortLabel: "YouTube",
    icon: "FaYoutube",
    color: "#FF0000",
    darkColor: "#FF0000",
    contentTypes: [
      { id: "idea", label: "Fikir" },
      { id: "script", label: "Script" },
      { id: "title", label: "Başlık" },
      { id: "description", label: "Açıklama" },
    ],
    endpoint: "/api/generate/youtube/script",
    placeholder: "YouTube video konusu yaz...",
    hasPersona: false,
    hasTone: false,
    hasKnowledge: false,
    hasStyleProfile: false,
    hasUltraMode: false,
  },
  tiktok: {
    id: "tiktok",
    label: "TikTok",
    shortLabel: "TikTok",
    icon: "FaTiktok",
    color: "#000000",
    darkColor: "#ffffff",
    contentTypes: [
      { id: "script", label: "Script" },
      { id: "caption", label: "Caption" },
    ],
    endpoint: "/api/generate/tiktok/script",
    placeholder: "TikTok video konusu yaz...",
    hasPersona: false,
    hasTone: false,
    hasKnowledge: false,
    hasStyleProfile: false,
    hasUltraMode: false,
  },
  blog: {
    id: "blog",
    label: "Blog",
    shortLabel: "Blog",
    icon: "HiDocumentText",
    color: "#6366F1",
    darkColor: "#818CF8",
    contentTypes: [
      { id: "draft", label: "Taslak" },
      { id: "full", label: "Tam Yazı" },
      { id: "seo", label: "SEO" },
    ],
    endpoint: "/api/generate/blog/full",
    placeholder: "Blog yazısı konusu yaz...",
    hasPersona: false,
    hasTone: false,
    hasKnowledge: false,
    hasStyleProfile: false,
    hasUltraMode: false,
  },
};

export const PLATFORM_LIST = Object.values(PLATFORMS);

export function getPlatform(id) {
  return PLATFORMS[id] || PLATFORMS.twitter;
}
